routes/admin.php
<?php


    Route::get('/dash', 'Dashboard\DashboardController@index');
    // Public :-


    Route::resource('/users', 'User\IndexController');
    Route::resource('/markters', 'Markter\IndexController');
    Route::resource('/sliders', 'Slider\IndexController');
    Route::resource('/trainers', 'Trainer\IndexController');
    Route::resource('/coordinators', 'Coordinators\IndexController');
    Route::resource('/financial_managements', 'Financial_management\IndexController');
    Route::resource('/courses', 'Course\IndexController');
     Route::resource('/archives', 'Archive\IndexController');
     Route::resource('/offers', 'Offer\IndexController');
     Route::resource('/categories', 'Category\IndexController');
     Route::resource('/licensed_course', 'Licensed_Course\IndexController');


// Active , deActive accounts ( user ) :-
    Route::get('/active_account/{id}', 'Active\ActiveAccountController@index');
    Route::get('/deActive_account/{id}', 'Active\ActiveAccountController@drActive_account');

Route::get('/paid_action/{id}', 'Active\ActiveAccountController@paid_action');
Route::get('/not_paid_action/{id}', 'Active\ActiveAccountController@not_paid_action');

Route::get('/confirm_course/{id}', 'Active\ActiveAccountController@confirm_course');
Route::get('/not_confirm_course/{id}', 'Active\ActiveAccountController@not_confirm_course');

Route::get('/send_email/{id}', 'Active\ActiveAccountController@send_email');
Route::get('/add_offer/{id}', 'Active\ActiveAccountController@add_offer');
Route::get('/cancel_offer/{id}', 'Active\ActiveAccountController@cancel_offer');




Route::resource('/orders', 'Order\IndexController');//
Route::resource('/order_requests', 'Request\IndexController');//

Route::get('/courses/{id}/orders', 'Order\IndexController@orders');//
//archives
Route::get('/archives/{id}/orders', 'Order\IndexController@archives');//
//order_requests
Route::get('/courses/{id}/order_requests', 'Request\IndexController@order_requests');//*/
Route::get('/courses/{id}/orders_advertisement', 'Request\IndexController@orders_advertisement');//*/
Route::resource('/contract_courses', 'Contract_courses\IndexController');//
   Route::resource('/setting', 'Setting\IndexController');//

Route::get('/markter_courses', 'Course\IndexController@markter_courses');
Route::get('/coordinators_courses', 'Course\IndexController@coordinators_courses');
Route::get('/financial_management', 'Course\IndexController@financial_management');



    Route::resource('/contact', 'Contact\IndexController');

Route::get('/userNotifiy/{id}', 'User\UserNotificationController@index');
Route::post('/userNotifiyStore', 'User\UserNotificationController@userNotifiyStore');


//
Route::get('/export-report_orders/{id}', 'ExcelController@report_orders');
Route::get('/export-orders_advertisement/{id}', 'ExcelController@orders_advertisement');



///
Route::resource('/terms_and_conditions', 'Term\IndexController');//

//
Route::resource('/complaints', 'Complaint\IndexController');


/* ZOOM ROUTES */
Route::group(['prefix' => 'zoom', 'as' => 'zoom.', 'namespace' => 'Zoom'], function () {
    Route::get('create', 'ZoomController@create')->name('create');
    Route::post('generate', 'ZoomController@generateMeeting')->name('generate-meeting');
});

routes/web.php
<?php

Route::get('/verfiyEmail/{id}/{code}', 'Admin\Auth\LoginController@verfiyEmail');
Route::view('/thanks_page', 'site.thanks_page');


Route::get('/admin', 'Admin\Auth\LoginController@index');
Route::get('/markter', 'Admin\Auth\LoginController@index');
Route::post('/adminlogin', 'Admin\Auth\LoginController@adminlogin');
Route::post('/adminlogout', 'Admin\Auth\LoginController@adminlogout');

//Confirm Register
Route::get('/register_form/{id}/{token}', 'Site\ConfirmRegister\IndexController@register_form');
Route::post('/confirm-register', 'Site\ConfirmRegister\IndexController@store');

//sponsored advertisement

Route::get('/sponsored_advertisement/{id}/{token}', 'Site\SponsoredAdvertisement\IndexController@sponsored_advertisement');
Route::post('/sponsored_advertisement', 'Site\SponsoredAdvertisement\IndexController@store');

Route::get('/', 'Site\Home\IndexController@index');
Route::get('/home', 'Site\Home\IndexController@index');
Route::get('/courses', 'Site\Home\IndexController@courses');
Route::get('/courseDetails/{id}', 'Site\Home\IndexController@courseDetails');
Route::post('/register-course', 'Site\Home\IndexController@registerCourse');

Route::get('/trainer-details/{id}', 'Site\Home\IndexController@trainerDetails');
Route::get('/offers', 'Site\Home\IndexController@offers');
Route::get('/archives', 'Site\Home\IndexController@archives');
Route::get('/table_courses', 'Site\Home\IndexController@table_courses');
Route::get('/licensed_courses', 'Site\Home\IndexController@licensed_courses');
Route::get('/contact', 'Site\Contact\IndexController@index');
Route::post('/contact-us', 'Site\Contact\IndexController@store');

Route::get('/contract_courses', 'Site\Contract_courses\IndexController@index');
Route::post('/make_contract_courses', 'Site\Contract_courses\IndexController@store');

// Search
Route::get('/search', 'Site\Search\IndexController@index');


// Terms And Conditions
Route::get('/terms_and_conditions', 'Site\TermsPage\IndexController@terms_and_conditions');

// Terms And Conditions
Route::get('/terms_and_conditions', 'Site\TermsPage\IndexController@terms_and_conditions');
Route::get('/e_learning', 'Site\TermsPage\IndexController@e_learning');
Route::get('/privacy', 'Site\TermsPage\IndexController@privacy');
Route::get('/property_rights', 'Site\TermsPage\IndexController@property_rights');
Route::get('/integrity', 'Site\TermsPage\IndexController@integrity');
Route::get('/cheat', 'Site\TermsPage\IndexController@cheat');


//
Route::get('/complaints', 'Site\Complaint\IndexController@index');
Route::post('/send_complaints', 'Site\Complaint\IndexController@store');


Route::get('/questionnaire', 'Site\Questionnaire\IndexController@index');
Route::post('/make_questionnaire', 'Site\Questionnaire\IndexController@store');


//register
Route::get('/register', 'Site\Register\IndexController@index');
Route::post('/siteRegisterForm', 'Site\Register\IndexController@siteRegisterForm');
Route::get('/verfiyMobilePage', 'Site\Register\IndexController@verfiyMobilePage');
Route::post('/verifyaccountWithemail', 'Site\Register\IndexController@verifyaccountWithemail');


//login
Route::get('/login', 'Site\Login\IndexController@index');
Route::post('/login_site', 'Site\Login\IndexController@login');
Route::get('/siteLogout', 'Site\Login\IndexController@siteLogout');

// User Profile
Route::get('/profile', 'Site\Profile\profileController@index');
Route::get('/editProfile', 'Site\Profile\profileController@editProfile');
Route::post('/updateProfile', 'Site\Profile\profileController@update');

/* ZOOM ROUTES */
Route::group(['prefix' => 'zoom', 'as' => 'zoom.', 'namespace' => 'Site\Zoom'], function () {
    Route::get('join', 'ZoomController@join')->name('join');
    Route::get('getRoom/{hostId}' , 'ZoomController@getRoom')->name('get-room');
});

app/User.php
<?php

    namespace App;

    use App\ModulesConst\UserVerify;
    use Illuminate\Notifications\Notifiable;
    use Illuminate\Contracts\Auth\MustVerifyEmail;
    use Illuminate\Foundation\Auth\User as Authenticatable;
    use Laravel\Passport\HasApiTokens;


    class User extends Authenticatable
    {
        use Notifiable, HasApiTokens;

        /**
         * The attributes that are mass assignable.
         *
         * @var array
         */
        protected $fillable = [
            'user_type_id',
            'social_id',
            'user_name',
            'name',
            'description',
            'image',
            'country_id',
            'city',
            'mobile',
            'mobile_verified',
            'email',
            'email_verified_at',
            'email_verified',
            'password',
            'fire_base_token',
            'passCode',
            'MobileCode',
            'address',
            'userVerify',
            'delivery_cost',
            'api_token',
        ];

        /**
         * The attributes that should be hidden for arrays.
         *
         * @var array
         */
        protected $hidden = [
            'password', 'remember_token',
        ];

        /**
         * The attributes that should be cast to native types.
         *
         * @var array
         */
        protected $casts = [
//            'created_at' => 'timestamp',
            'email_verified_at' => 'bool',
            'mobile_verified_at' => 'datetime',
            'email_verified' => 'boolean',
            'online_at' => 'datetime',
            'online' => 'boolean',
            'userVerify' => 'boolean',
            'mobile_verified' => 'boolean',
            'need_reset_password' => 'boolean',
        ];

        public function toArray()
        {
            $data["id"] = $this->id;
/*            $data["image"] = $this->image;
            $data["social_id"] = $this->social_id;*/
            $data["user_type_id"] = $this->user_type_id;
            $data["userVerify"] = $this->userVerify;
            $data["name"] = $this->name;
/*            $data["description"] = $this->description;*/
            $data["mobile"] = $this->mobile;
            $data["email"] = $this->email;
            $data["join_from"] = $this->join_from();
            $data["is_data_complete"] = $this->is_data_complete();
            return $data;
        }

        public function profile()
        {
            $data["id"] = $this->id;
            /*$data["image"] = $this->image;
            $data["social_id"] = $this->social_id;*/
            $data["user_type_id"] = $this->user_type_id;
            $data["userVerify"] = $this->userVerify;
            $data["name"] = $this->name;
/*            $data["description"] = $this->description;*/
            $data["mobile"] = $this->mobile;
            $data["email"] = $this->email;
            $data["join_from"] = $this->join_from();
            $data["is_data_complete"] = $this->is_data_complete();
            return $data;
        }


        public function is_data_complete()
        {
            if (!$this->name and !$this->email) {
                return false;
            }
            return true;
        }

        public function lastpasswords()
        {
            return $this->hasMany('App\User_lastpasswords', 'user_id');
        }

        public function user_type()
        {
            return $this->belongsTo(User_type::class, 'user_type_id');
        }


        public function country()
        {
            return $this->belongsTo(Country::class, 'country_id');
        }

        public function categories_list()
        {
            $sub_cats_ids = Shop_categories::where('user_id', $this->id)->pluck('sub_category_id');
            $cats = Sub_category::whereIn('id', $sub_cats_ids)->orderBy('id', 'desc')->get();
            return $cats;
        }


        public function bank()
        {
            return $this->belongsTo(Bank::class, 'bank_id');
        }

        public function accessTokens()
        {
            return $this->hasMany('App\OauthAccessToken');
        }


        public function getDashNameAttribute()
        {
            $attribute =  trans('language.notSelected');
            if ($this->name)
                $attribute = $this->name;
            return $attribute;
        }


        public function getDashEmailAttribute()
        {
            $attribute =  trans('language.notSelected');
            if ($this->email)
                $attribute = $this->email;
            return $attribute;
        }

        public function getDashMobileAttribute()
        {
            $attribute =  trans('language.notSelected');
            if ($this->mobile)
                $attribute = $this->mobile;
            return $attribute;
        }



        public function getDashStatusNameAttribute()
        {
            if ($this->userVerify == UserVerify::yes) {
                return trans("language.verfied");
            } else {
                return trans("language.not_verfied");
            }
        }

        public function getDashImageAttribute()
        {
            if ($this->image)
                return $attribute = $this->image;
            else
                return "https://cdn3.iconfinder.com/data/icons/avatars-round-flat/33/avat-01-512.png";
        }

        public function getServCityAttribute()
        {
            $att = trans('language.notSelected');
            if ($this->city) {
                $att = $this->city->serv_name;
            }
            return $att;
        }


        public function getServDistractAttribute()
        {
            $att = trans('language.notSelected');
            if ($this->district) {
                $att = $this->district->serv_name;
            }
            return $att;
        }

        public function getServUserTypeNameAttribute()
        {
            $att = trans('language.notSelected');
            if ($this->user_type) {
                $att = $this->user_type->serv_name;
            }
            return $att;
        }

        public function is_block()
        {
            if ($this->block_date != null) {
                return true;
            } else {
                return false;
            }
        }


        public function getServBlockDateAttribute()
        {
            if ($this->block_date != null) {
                $now_time = strtotime(now()) * 1000;
                return $now_time;
            } else {
                return false;
            }
        }

        public function roles()
        {
            return $this->belongsToMany(Role::class);
        }

        public function authorizeRoles($roles)
        {
            if (is_array($roles)) {
                return $this->hasAnyRole($roles) ||
                    abort(401, 'This action is unauthorized.');
            }
            return $this->hasRole($roles) ||
                abort(401, 'This action is unauthorized.');
        }

        public function hasAnyRole($roles)
        {
            return null !== $this->roles()->whereIn(‘name’, $roles)->first();
        }

        public function hasRole($role)
        {
            return null !== $this->roles()->where(‘name’, $role)->first();
        }


        // Shop Relations :-
        public function services_list()
        {
            $service_ids = User_service::where("user_id", $this->id)->pluck('service_id');
            $servies = Service::whereIn('id', $service_ids)->get();
            return $servies;
        }


        public function provider_service_sections_list()
        {
            $service_ids = User_service::where("user_id", $this->id)->pluck('service_id');
            $servies = User_service_section::whereIn('id', $service_ids)->get();
            return $servies;
        }

        public function join_from()
        {
            return $this->created_at->diffforhumans();
        }


        public function shop_images()
        {
            return Shop_images::where('user_id', $this->id)->get();
        }

        public function postion()
        {
            $trainer= Trainer::where('user_id', $this->id)->first();
            //dd($trainer);
            return $trainer->current_position;
        }
    }

app/Http/Controllers/Admin/Archive/IndexController.php
<?php

namespace App\Http\Controllers\Admin\Archive;
use Carbon\Carbon;

use App\Course;
use App\Traits\storeImage;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    use storeImage;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $date = Carbon::now()->format('Y-m-d');
        $items = Course::where("end_date","<",$date);
        $items = $this->filter($request, $items);
        return view('admin.courses.archives', compact('items'));
    }

    public function filter($request, $items)
    {

        if ($request->name)
            $items = $items->where("name", 'LIKE', '%' . $request->name . '%');

        $items = $items->orderBy("id", "desc")->paginate(10);
        return $items;
    }
    public function destroy($id)
    {
        Course::findOrFail($id)->delete();
        session()->flash('success', trans('language.done'));
        return redirect(url('/admin/archives'));
    }
}

app/Http/Controllers/Site/AjaxController/IndexController.php
<?php

    namespace App\Http\Controllers\Site\AjaxController;

    use App\Categories;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;

    class IndexController extends Controller
    {
        public function getCategories(Request $request)
        {
            $categories = Categories::where("parent_id", $request->category_id)->orderBy("sort","desc")->get();
            $data['categories'] = $categories;
            if (count($categories) > 0) {
                $data["status"] = true;
            } else {
                $data["status"] = false;
            }
            return response()->json($data);
        }
    }

app/Http/Controllers/Site/Complaint/IndexController.php
<?php

    namespace App\Http\Controllers\Site\Complaint;

    use App\Complaints;
    use App\Contact_us;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;

    class IndexController extends Controller
    {
        public function index()
        {
            return view("site.complaints.index");
        }

        public function store(Request $request)
        {
            //dd("ghfhf");
            $data = $request->all();
            $contact=Complaints::create($data);
           //dd($msg);

            alert()->success('تم ارسال الشكوى بنجاح');
            return back();
        }
    }

resources/views/site/archives/index.blade.php
@extends('.site.layout.container')
@section('title','الأرشيف')
@section('content')

    <!--====== Page Banner Start ======-->

    <section class="page-banner">
        <div class="page-banner-bg " style="background-image: url({{asset("/assets/site")}}/images/page-banner.jpg);">
            <div class="container">
                <div class="banner-content text-center">
                    <h2 class="title"> الأرشيف</h2>
                </div>
            </div>
        </div>
    </section>

    <!--====== Page Banner Ends ======-->

    <section class="blog-page">
        <div class="container">
            <div class="row rtl-direction">
                <div class="col-lg-12">
                    <form method="get" action="{{url("/archives/")}}">

                        <div style="display: flex">
                            <div class="col-md-3">
                                <select class="form-control" name="category_id">
                                    <option value="">{{trans('language.category')}}</option>
                                    @foreach(\App\Category::all() as $selectItem)
                                        <option value="{{$selectItem->id}}">{{$selectItem->dash_name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-3">
                                <input style="width: 45%" type="submit" class="btn btn-success " value="{{trans('language.filter')}}">
                                <button style="width: 45%" type="button"
                                        class="btn btn-info  reset_inputs ">{{trans('language.reset')}}</button>
                            </div>

                        </div>
                    </form>
                    <br>
                    @foreach ($items as $course)
                        <div class="col-lg-4 col-md-6 flo-right">
                            <div class="single-blog mt-30">
                                <div class="blog-image">
                                    <a href="{{url("/courseDetails/$course->id")}}">
                                        <img src="{{$course->image}}" alt="blog">
                                    </a>
                                </div>
                                <div class="blog-content">
                                    <h4 class="blog-title text-right"><a href="{{url("/courseDetails/$course->id")}}">{{$course->name}}</a></h4>
                                    <a href="{{url("/courseDetails/$course->id")}}" class="more"><i class="fal fa-chevron-left"></i> المزيد </a>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
            <ul class="pagination-items text-center">
                {{$items->links()}}
            </ul>
        </div>
    </section>
    <!--====== Counter Start ======-->

    <div class="counter-area-2">
        <div class="container">
            <div class="counter-wrapper-2 " style="background-image: url({{asset("/assets/site")}}/images/counter-bg-2.jpg);">
                <div class="row">
                    <div class="col-sm-3 col-6 counter-col">
                        <div class="single-counter mt-30">
                            <span class="counter-count"><span class="count">3652</span> +</span>
                            <p>الطلاب</p>
                        </div>
                    </div>
                    <div class="col-sm-3 col-6 counter-col">
                        <div class="single-counter mt-30">
                            <span class="counter-count"><span class="count">105</span> +</span>
                            <p>المدرسين</p>
                        </div>
                    </div>
                    <div class="col-sm-3 col-6 counter-col">
                        <div class="single-counter mt-30">
                            <span class="counter-count"><span class="count">120</span> +</span>
                            <p>الدورات</p>
                        </div>
                    </div>
                    <div class="col-sm-3 col-6 counter-col">
                        <div class="single-counter mt-30">
                            <span class="counter-count"><span class="count">30</span> +</span>
                            <p>الجوائز</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--====== Counter Ends ======-->


@endsection
@section('extra_css')
 {{--   <style>
        .footer_sticky_part {
            padding-top: 100px !important;
        }
    </style>--}}
@endsection